services:
  qr-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-code-generator-app
    container_name: qr-generator
    environment:
      QR_CODES_DIR: /app/qr_codes
      LOGS_DIR: /app/logs
    volumes:
      - ./qr_codes:/app/qr_codes
      - ./logs:/app/logs
    command: ["--url", "https://www.njit.edu"]
