import * as fs from 'fs';
import * as path from 'path';

/**
 * FileService
 * 
 * Handles file I/O operations for storing research and references.
 * Follows SOLID: Single Responsibility Principle
 */

export class FileService {
  private referencesDir: string;
  private aiFeedbackDir: string;

  constructor(baseDir: string = process.cwd()) {
    this.referencesDir = path.join(baseDir, 'references');
    this.aiFeedbackDir = path.join(this.referencesDir, 'ai_feedback');
    this.ensureDirectories();
  }

  /**
   * Ensure all required directories exist
   */
  private ensureDirectories(): void {
    if (!fs.existsSync(this.referencesDir)) {
      fs.mkdirSync(this.referencesDir, { recursive: true });
    }
    if (!fs.existsSync(this.aiFeedbackDir)) {
      fs.mkdirSync(this.aiFeedbackDir, { recursive: true });
    }
  }

  /**
   * Save search results to a markdown file
   */
  saveSearchResult(query: string, content: string): string {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').split('T')[0];
    const sanitizedQuery = query
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .substring(0, 50);

    const filename = `search_${sanitizedQuery}_${timestamp}.md`;
    const filepath = path.join(this.referencesDir, filename);

    const markdown = `# Research: ${query}

**Date:** ${new Date().toLocaleString()}  
**Query:** ${query}

---

${content}

---

*Generated by CLI AI Toolkit*
`;

    fs.writeFileSync(filepath, markdown, 'utf-8');
    return filepath;
  }

  /**
   * Save AI feedback/analysis results to ai_feedback folder
   */
  saveAiFeedback(filename: string, content: string): string {
    // Ensure filename doesn't have path traversal
    const safeName = filename.replace(/[^a-z0-9._-]/gi, '_');
    const filepath = path.join(this.aiFeedbackDir, safeName);

    const markdown = `# AI Analysis Result

**Date:** ${new Date().toLocaleString()}  
**File:** ${filename}

---

${content}

---

*Generated by CLI AI Toolkit - Gemini 3 Analysis*
`;

    fs.writeFileSync(filepath, markdown, 'utf-8');
    return filepath;
  }

  /**
   * Get all files in references directory
   */
  getReferencesFiles(): string[] {
    if (!fs.existsSync(this.referencesDir)) {
      return [];
    }
    return fs.readdirSync(this.referencesDir);
  }

  /**
   * Get all files in ai_feedback directory
   */
  getAiFeedbackFiles(): string[] {
    if (!fs.existsSync(this.aiFeedbackDir)) {
      return [];
    }
    return fs.readdirSync(this.aiFeedbackDir);
  }

  /**
   * Get the references directory path
   */
  getReferencesDir(): string {
    return this.referencesDir;
  }

  /**
   * Get the ai_feedback directory path
   */
  getAiFeedbackDir(): string {
    return this.aiFeedbackDir;
  }

  /**
   * Check if file exists
   */
  fileExists(filepath: string): boolean {
    return fs.existsSync(filepath);
  }

  /**
   * Read file as base64
   */
  readFileAsBase64(filepath: string): string {
    const buffer = fs.readFileSync(filepath);
    return buffer.toString('base64');
  }

  /**
   * Get MIME type from file extension
   */
  getMimeType(filepath: string): string {
    const ext = path.extname(filepath).toLowerCase();
    const mimes: { [key: string]: string } = {
      '.jpg': 'image/jpeg',
      '.jpeg': 'image/jpeg',
      '.png': 'image/png',
      '.gif': 'image/gif',
      '.webp': 'image/webp',
      '.mp4': 'video/mp4',
      '.avi': 'video/x-msvideo',
      '.mov': 'video/quicktime',
      '.mkv': 'video/x-matroska',
      '.webm': 'video/webm',
    };
    return mimes[ext] || 'application/octet-stream';
  }
}
